import Head from "next/head";
import Image from "next/image";
import {Inter} from "next/font/google";
import styles from "@/styles/Home.module.scss";
import pagestyles from "@/styles/home/Main.module.scss";
import {useDispatch, useSelector} from "react-redux";
import {useEffect, useRef} from "react";
import {closeNav, setNav} from "@/redux-actions/homeNavSlice";
import Footer from "@/components/home/Footer";
import Header from "@/components/home/Header";
import {Card, CardBody, Heading, Link} from "@chakra-ui/react";
import TopWidget from "@/components/pages/TopWidget";
import BottomWidget from "@/components/pages/BottomWidget";
import NotificationPopup from "@/components/home/NotificationPopup";
import {SiWhatsapp} from "react-icons/si";
import MainLayout from "../layout/Mainlayout";

const inter = Inter({subsets: ["latin"]});

export default function Index() {
  const {openNav} = useSelector((state: any) => state.nav);
  const dispatch = useDispatch();
  const sideNavRef: any = useRef();

  const handleClickOutside = (event: any) => {
    if (sideNavRef.current && !sideNavRef.current.contains(event.target)) {
      dispatch(closeNav());
    }
  };
  useEffect(() => {
    const navState = localStorage.getItem("home-nav");
    let navstate = navState ? JSON.parse(navState) : null;
    if (navstate) {
      dispatch(setNav(navstate));
    }
  }, []);

  useEffect(() => {
    document.addEventListener("click", handleClickOutside);

    return () => {
      document.removeEventListener("click", handleClickOutside);
    };
  }, []);
  return (
    <>
      <Head>
        <title>Purchase | GLOBAL TYCOON FX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo2-transparent.png" />
      </Head>
      <MainLayout>
        <main className={` ${pagestyles.body} ${pagestyles.top_head}`}>
          <Heading fontSize={28} textTransform={"uppercase"}>
            How To Buy Crypto
          </Heading>
          <div className={` ${pagestyles.bc_lists}`}>
            <Heading fontSize={20}>Follow these Steps to carefully</Heading>
            <ol>
              <li>Copy the address of your desired crypto payment</li>
              <li>
                Visit{" "}
                <Link href={"https://www.moonpay.com/"}>www.moonpay.com</Link>{" "}
              </li>
              <li>Select the type of Crypto</li>
              <li>Enter and Continue</li>
              <li>Enter the company wallet address and Continue</li>
              <li>Enter Your Email address and continue</li>
              <li>Enter verification code and continue</li>
              <li>
                Please enter your name and date of birth as they appear on
                official documents. Inaccurate information will delay the
                completion of your transaction
              </li>
            </ol>
          </div>
        </main>
      </MainLayout>
    </>
  );
}
